apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: hello-world-flask
  template:
    metadata:
      labels:
        deployment: hello-world-flask
    spec:
      containers:
      - name: flask-python-container
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 5000
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: the-map
              key: enableRisky