kind: Service
apiVersion: v1
metadata:
  name: service-nodeport
spec:
  selector:
    deployment: hello-world-flask
    app: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000